apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: my-flask-app
        image: 80081837/mypythonflaskwebapp
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
     
        
        ports:
        - containerPort: 5000
        
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
